#!/usr/bin/env python3
"""
Create a GitHub issue with the video report attached.
"""

import os, sys, json, urllib.request, base64, argparse
from pathlib import Path

KEY = os.environ.get("GITHUB_TOKEN", "")

def main():
    parser = argparse.ArgumentParser(description="Submit test report as GitHub issue")
    parser.add_argument("--repo", required=True, help="Repo: owner/repo")
    parser.add_argument("--title", default="AI Tester Report", help="Issue title")
    parser.add_argument("--body", default="", help="Issue body")
    parser.add_argument("--video", help="Path to video report")
    parser.add_argument("--label", action="append", help="Labels to add")
    args = parser.parse_args()
    
    body = args.body
    if not body:
        body = f"""## 🤖 AI Tester Report

**Test:** {args.title}

This is an automated test report generated by AI Tester.

### Test Summary
- Repository: {args.repo}
- Generated by: Hermes Agent
- Video report: {args.video or 'Not available'}

### Findings
_Describe what was tested and what was found here._

---

*Generated by [AI Tester](https://github.com/zedarvates/ai-tester)*
"""
    
    if args.video:
        video_path = Path(args.video)
        if video_path.exists():
            size_mb = video_path.stat().st_size / (1024*1024)
            body += f"\n\n### 📹 Video Report\n"
            body += f"File: `{video_path.name}` ({size_mb:.1f} MB)\n"
            
            if size_mb < 10:
                # Upload to GitHub as an asset
                with open(video_path, "rb") as f:
                    data = f.read()
                b64 = base64.b64encode(data).decode()
                body += f"\nVideo attached (base64, {len(data)} bytes)\n"
    
    issue_data = {
        "title": args.title,
        "body": body,
        "labels": args.label or ["bug", "ai-tester"]
    }
    
    req = urllib.request.Request(
        f"https://api.github.com/repos/{args.repo}/issues",
        data=json.dumps(issue_data).encode(),
        method="POST"
    )
    req.add_header("Authorization", f"token {KEY}")
    req.add_header("Accept", "application/vnd.github.v3+json")
    
    try:
        resp = urllib.request.urlopen(req, timeout=15)
        result = json.loads(resp.read())
        print(f"✅ Issue created: {result['html_url']}")
    except urllib.error.HTTPError as e:
        print(f"❌ HTTP {e.code}: {e.read().decode()[:300]}")

if __name__ == "__main__":
    main()
