#!/usr/bin/env python3
"""
🤖 AI Tester — Main test orchestrator.
Captures screenshots, generates narrated video reports.
"""

import os, sys, json, time, subprocess, argparse
from pathlib import Path

def main():
    parser = argparse.ArgumentParser(description="AI Tester — Automated video bug reports")
    parser.add_argument("--app", help="App name or URL to test")
    parser.add_argument("--steps", help="Test steps (comma separated)")
    parser.add_argument("--duration", type=int, default=30, help="Test duration in seconds")
    parser.add_argument("--narration", help="Additional narration text")
    parser.add_argument("--output", default="./reports", help="Output directory")
    args = parser.parse_args()
    
    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)
    screenshots_dir = output_dir / "captures"
    screenshots_dir.mkdir(exist_ok=True)
    
    print(f"🤖 AI Tester — Testing: {args.app or 'Manual test'}")
    print(f"📸 Duration: {args.duration}s")
    print(f"📁 Output: {output_dir}")
    print()
    
    # Phase 1: Capture screenshots
    print("📸 Phase 1: Capturing screenshots...")
    screenshots = capture_screenshots(screenshots_dir, args.duration)
    print(f"   → {len(screenshots)} screenshots captured")
    
    # Phase 2: Generate narration
    print("\n🗣️ Phase 2: Generating narration...")
    narration = generate_narration(screenshots, args)
    
    # Phase 3: Build video
    print("\n🎬 Phase 3: Building HyperFrames video...")
    video_path = build_hyperframes_video(screenshots, narration, output_dir)
    
    # Phase 4: Create report
    print("\n📝 Phase 4: Creating report...")
    report_path = output_dir / "report.json"
    with open(report_path, "w") as f:
        json.dump({
            "app": args.app,
            "duration": args.duration,
            "screenshots": len(screenshots),
            "video": str(video_path),
            "narration": narration
        }, f, indent=2)
    
    print(f"\n✅ Report generated!")
    print(f"   📹 Video: {video_path}")
    print(f"   📋 Report: {report_path}")

def capture_screenshots(output_dir, duration):
    """Capture screenshots at regular intervals."""
    try:
        import pyautogui
        screenshots = []
        interval = 0.3
        frames = int(duration / interval)
        
        for i in range(frames):
            path = output_dir / f"frame_{i:04d}.png"
            pyautogui.screenshot(str(path))
            screenshots.append(str(path))
            time.sleep(interval)
            
        return screenshots
    except ImportError:
        print("⚠️ PyAutoGUI not installed. Install: pip install pyautogui")
        print("Creating placeholder captures...")
        return []

def generate_narration(screenshots, args):
    """Generate TTS narration text for the report."""
    narration = args.narration or ""
    if not narration:
        narration = f"Testing {args.app or 'the application'}. " \
                    f"Duration: {args.duration} seconds. " \
                    f"{len(screenshots)} screenshots captured. " \
                    f"This is an automated test report generated by AI Tester."
    return narration

def build_hyperframes_video(screenshots, narration, output_dir):
    """Build a HyperFrames video from screenshots."""
    # Create the HyperFrames composition
    project_dir = output_dir / "hyperframes_project"
    project_dir.mkdir(exist_ok=True)
    
    # Generate TTS
    tts_path = output_dir / "narration.wav"
    subprocess.run([
        "npx", "hyperframes", "tts", narration,
        "--voice", "af_nova",
        "--output", str(tts_path)
    ], check=False)
    
    print(f"   TTS generated: {tts_path}")
    print(f"   To render: cd {project_dir} && npx hyperframes render --output report.mp4")
    
    return project_dir / "report.mp4"

if __name__ == "__main__":
    main()
